apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorviz-trace-service
  labels:
    app: explorviz-trace-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorviz-trace-service
  template:
    metadata:
      labels:
        app: explorviz-trace-service
    spec:
      containers:
      - name: explorviz-trace-service
        image: explorviz/trace-service-jvm:latest
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: explorviz-trace-service
  labels:
    app: explorviz-trace-service
spec:
  type: NodePort
  ports:
    - name: explorviz-trace-service
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32681
  selector:
    app: explorviz-trace-service

