// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: token_event.proto

package tokenpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_CREATED        EventType = 0
	EventType_DELETED        EventType = 1
	EventType_CLONED         EventType = 2
	EventType_ACCESS_GRANTED EventType = 3
	EventType_ACCESS_REVOKED EventType = 4
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "CREATED",
		1: "DELETED",
		2: "CLONED",
		3: "ACCESS_GRANTED",
		4: "ACCESS_REVOKED",
	}
	EventType_value = map[string]int32{
		"CREATED":        0,
		"DELETED":        1,
		"CLONED":         2,
		"ACCESS_GRANTED": 3,
		"ACCESS_REVOKED": 4,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_token_event_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_token_event_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_token_event_proto_rawDescGZIP(), []int{0}
}

type TokenEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=EventType" json:"type,omitempty"`
	Token         *LandscapeToken        `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ClonedTokenId *string                `protobuf:"bytes,3,opt,name=cloned_token_id,json=clonedTokenId,proto3,oneof" json:"cloned_token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenEvent) Reset() {
	*x = TokenEvent{}
	mi := &file_token_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenEvent) ProtoMessage() {}

func (x *TokenEvent) ProtoReflect() protoreflect.Message {
	mi := &file_token_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenEvent.ProtoReflect.Descriptor instead.
func (*TokenEvent) Descriptor() ([]byte, []int) {
	return file_token_event_proto_rawDescGZIP(), []int{0}
}

func (x *TokenEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_CREATED
}

func (x *TokenEvent) GetToken() *LandscapeToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *TokenEvent) GetClonedTokenId() string {
	if x != nil && x.ClonedTokenId != nil {
		return *x.ClonedTokenId
	}
	return ""
}

type LandscapeToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	OwnerId       string                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Created       uint64                 `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LandscapeToken) Reset() {
	*x = LandscapeToken{}
	mi := &file_token_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LandscapeToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandscapeToken) ProtoMessage() {}

func (x *LandscapeToken) ProtoReflect() protoreflect.Message {
	mi := &file_token_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandscapeToken.ProtoReflect.Descriptor instead.
func (*LandscapeToken) Descriptor() ([]byte, []int) {
	return file_token_event_proto_rawDescGZIP(), []int{1}
}

func (x *LandscapeToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LandscapeToken) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *LandscapeToken) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *LandscapeToken) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *LandscapeToken) GetCreated() uint64 {
	if x != nil {
		return x.Created
	}
	return 0
}

var File_token_event_proto protoreflect.FileDescriptor

const file_token_event_proto_rawDesc = "" +
	"\n" +
	"\x11token_event.proto\"\x94\x01\n" +
	"\n" +
	"TokenEvent\x12\x1e\n" +
	"\x04type\x18\x01 \x01(\x0e2\n" +
	".EventTypeR\x04type\x12%\n" +
	"\x05token\x18\x02 \x01(\v2\x0f.LandscapeTokenR\x05token\x12+\n" +
	"\x0fcloned_token_id\x18\x03 \x01(\tH\x00R\rclonedTokenId\x88\x01\x01B\x12\n" +
	"\x10_cloned_token_id\"\x83\x01\n" +
	"\x0eLandscapeToken\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\x12\x18\n" +
	"\acreated\x18\x05 \x01(\x04R\acreated*Y\n" +
	"\tEventType\x12\v\n" +
	"\aCREATED\x10\x00\x12\v\n" +
	"\aDELETED\x10\x01\x12\n" +
	"\n" +
	"\x06CLONED\x10\x02\x12\x12\n" +
	"\x0eACCESS_GRANTED\x10\x03\x12\x12\n" +
	"\x0eACCESS_REVOKED\x10\x04B>Z<github.com/ExplorViz/trace-service/internal/genproto/tokenpbb\x06proto3"

var (
	file_token_event_proto_rawDescOnce sync.Once
	file_token_event_proto_rawDescData []byte
)

func file_token_event_proto_rawDescGZIP() []byte {
	file_token_event_proto_rawDescOnce.Do(func() {
		file_token_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_token_event_proto_rawDesc), len(file_token_event_proto_rawDesc)))
	})
	return file_token_event_proto_rawDescData
}

var file_token_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_token_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_token_event_proto_goTypes = []any{
	(EventType)(0),         // 0: EventType
	(*TokenEvent)(nil),     // 1: TokenEvent
	(*LandscapeToken)(nil), // 2: LandscapeToken
}
var file_token_event_proto_depIdxs = []int32{
	0, // 0: TokenEvent.type:type_name -> EventType
	2, // 1: TokenEvent.token:type_name -> LandscapeToken
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_token_event_proto_init() }
func file_token_event_proto_init() {
	if File_token_event_proto != nil {
		return
	}
	file_token_event_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_token_event_proto_rawDesc), len(file_token_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_token_event_proto_goTypes,
		DependencyIndexes: file_token_event_proto_depIdxs,
		EnumInfos:         file_token_event_proto_enumTypes,
		MessageInfos:      file_token_event_proto_msgTypes,
	}.Build()
	File_token_event_proto = out.File
	file_token_event_proto_goTypes = nil
	file_token_event_proto_depIdxs = nil
}
