services:
  otel-collector:
    image: explorviz/otel-collector
    hostname: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    restart: on-failure
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 55678:55678

  clickhouse:
    image: clickhouse/clickhouse-server:26.5
    hostname: clickhouse
    restart: always
    ports:
      - 8123:8123
      - 19000:9000
    volumes:
      - .:/docker-entrypoint-initdb.d
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  trace-generator:
    image: explorviz/trace-generator
    ports:
      - 8079:8079
    extra_hosts:
      - "localhost:host-gateway"
