// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: parsed_span.proto

package spanpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParsedSpan struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LandscapeTokenId     string                 `protobuf:"bytes,1,opt,name=landscape_token_id,json=landscapeTokenId,proto3" json:"landscape_token_id,omitempty"`
	LandscapeTokenSecret string                 `protobuf:"bytes,2,opt,name=landscape_token_secret,json=landscapeTokenSecret,proto3" json:"landscape_token_secret,omitempty"`
	TraceId              string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId               string                 `protobuf:"bytes,4,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	SpanName             string                 `protobuf:"bytes,5,opt,name=span_name,json=spanName,proto3" json:"span_name,omitempty"`
	ParentId             *string                `protobuf:"bytes,6,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	StartTime            uint64                 `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              uint64                 `protobuf:"varint,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	ApplicationName      string                 `protobuf:"bytes,9,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	EntityId             string                 `protobuf:"bytes,10,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // Identifier for the entity described by the span (e.g. function, database, ...)
	// Types that are valid to be assigned to EntityDescriptor:
	//
	//	*ParsedSpan_CodeDescriptor
	EntityDescriptor isParsedSpan_EntityDescriptor `protobuf_oneof:"entity_descriptor"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ParsedSpan) Reset() {
	*x = ParsedSpan{}
	mi := &file_parsed_span_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedSpan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedSpan) ProtoMessage() {}

func (x *ParsedSpan) ProtoReflect() protoreflect.Message {
	mi := &file_parsed_span_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedSpan.ProtoReflect.Descriptor instead.
func (*ParsedSpan) Descriptor() ([]byte, []int) {
	return file_parsed_span_proto_rawDescGZIP(), []int{0}
}

func (x *ParsedSpan) GetLandscapeTokenId() string {
	if x != nil {
		return x.LandscapeTokenId
	}
	return ""
}

func (x *ParsedSpan) GetLandscapeTokenSecret() string {
	if x != nil {
		return x.LandscapeTokenSecret
	}
	return ""
}

func (x *ParsedSpan) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ParsedSpan) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *ParsedSpan) GetSpanName() string {
	if x != nil {
		return x.SpanName
	}
	return ""
}

func (x *ParsedSpan) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *ParsedSpan) GetStartTime() uint64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ParsedSpan) GetEndTime() uint64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *ParsedSpan) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *ParsedSpan) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ParsedSpan) GetEntityDescriptor() isParsedSpan_EntityDescriptor {
	if x != nil {
		return x.EntityDescriptor
	}
	return nil
}

func (x *ParsedSpan) GetCodeDescriptor() *CodeDescriptor {
	if x != nil {
		if x, ok := x.EntityDescriptor.(*ParsedSpan_CodeDescriptor); ok {
			return x.CodeDescriptor
		}
	}
	return nil
}

type isParsedSpan_EntityDescriptor interface {
	isParsedSpan_EntityDescriptor()
}

type ParsedSpan_CodeDescriptor struct {
	CodeDescriptor *CodeDescriptor `protobuf:"bytes,11,opt,name=code_descriptor,json=codeDescriptor,proto3,oneof"`
}

func (*ParsedSpan_CodeDescriptor) isParsedSpan_EntityDescriptor() {}

type CodeDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FunctionName  string                 `protobuf:"bytes,2,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	ClassName     *string                `protobuf:"bytes,3,opt,name=class_name,json=className,proto3,oneof" json:"class_name,omitempty"` // Inner classes may be separated by "."
	Language      *string                `protobuf:"bytes,4,opt,name=language,proto3,oneof" json:"language,omitempty"`
	GitCommitHash *string                `protobuf:"bytes,5,opt,name=git_commit_hash,json=gitCommitHash,proto3,oneof" json:"git_commit_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeDescriptor) Reset() {
	*x = CodeDescriptor{}
	mi := &file_parsed_span_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeDescriptor) ProtoMessage() {}

func (x *CodeDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_parsed_span_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeDescriptor.ProtoReflect.Descriptor instead.
func (*CodeDescriptor) Descriptor() ([]byte, []int) {
	return file_parsed_span_proto_rawDescGZIP(), []int{1}
}

func (x *CodeDescriptor) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *CodeDescriptor) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *CodeDescriptor) GetClassName() string {
	if x != nil && x.ClassName != nil {
		return *x.ClassName
	}
	return ""
}

func (x *CodeDescriptor) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *CodeDescriptor) GetGitCommitHash() string {
	if x != nil && x.GitCommitHash != nil {
		return *x.GitCommitHash
	}
	return ""
}

var File_parsed_span_proto protoreflect.FileDescriptor

const file_parsed_span_proto_rawDesc = "" +
	"\n" +
	"\x11parsed_span.proto\"\xc4\x03\n" +
	"\n" +
	"ParsedSpan\x12,\n" +
	"\x12landscape_token_id\x18\x01 \x01(\tR\x10landscapeTokenId\x124\n" +
	"\x16landscape_token_secret\x18\x02 \x01(\tR\x14landscapeTokenSecret\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x04 \x01(\tR\x06spanId\x12\x1b\n" +
	"\tspan_name\x18\x05 \x01(\tR\bspanName\x12 \n" +
	"\tparent_id\x18\x06 \x01(\tH\x01R\bparentId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\x04R\tstartTime\x12\x19\n" +
	"\bend_time\x18\b \x01(\x04R\aendTime\x12)\n" +
	"\x10application_name\x18\t \x01(\tR\x0fapplicationName\x12\x1b\n" +
	"\tentity_id\x18\n" +
	" \x01(\tR\bentityId\x12:\n" +
	"\x0fcode_descriptor\x18\v \x01(\v2\x0f.CodeDescriptorH\x00R\x0ecodeDescriptorB\x13\n" +
	"\x11entity_descriptorB\f\n" +
	"\n" +
	"_parent_id\"\xf4\x01\n" +
	"\x0eCodeDescriptor\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12#\n" +
	"\rfunction_name\x18\x02 \x01(\tR\ffunctionName\x12\"\n" +
	"\n" +
	"class_name\x18\x03 \x01(\tH\x00R\tclassName\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\x04 \x01(\tH\x01R\blanguage\x88\x01\x01\x12+\n" +
	"\x0fgit_commit_hash\x18\x05 \x01(\tH\x02R\rgitCommitHash\x88\x01\x01B\r\n" +
	"\v_class_nameB\v\n" +
	"\t_languageB\x12\n" +
	"\x10_git_commit_hashB=Z;github.com/ExplorViz/trace-service/internal/genproto/spanpbb\x06proto3"

var (
	file_parsed_span_proto_rawDescOnce sync.Once
	file_parsed_span_proto_rawDescData []byte
)

func file_parsed_span_proto_rawDescGZIP() []byte {
	file_parsed_span_proto_rawDescOnce.Do(func() {
		file_parsed_span_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_parsed_span_proto_rawDesc), len(file_parsed_span_proto_rawDesc)))
	})
	return file_parsed_span_proto_rawDescData
}

var file_parsed_span_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_parsed_span_proto_goTypes = []any{
	(*ParsedSpan)(nil),     // 0: ParsedSpan
	(*CodeDescriptor)(nil), // 1: CodeDescriptor
}
var file_parsed_span_proto_depIdxs = []int32{
	1, // 0: ParsedSpan.code_descriptor:type_name -> CodeDescriptor
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_parsed_span_proto_init() }
func file_parsed_span_proto_init() {
	if File_parsed_span_proto != nil {
		return
	}
	file_parsed_span_proto_msgTypes[0].OneofWrappers = []any{
		(*ParsedSpan_CodeDescriptor)(nil),
	}
	file_parsed_span_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_parsed_span_proto_rawDesc), len(file_parsed_span_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_parsed_span_proto_goTypes,
		DependencyIndexes: file_parsed_span_proto_depIdxs,
		MessageInfos:      file_parsed_span_proto_msgTypes,
	}.Build()
	File_parsed_span_proto = out.File
	file_parsed_span_proto_goTypes = nil
	file_parsed_span_proto_depIdxs = nil
}
